### ISSUE TITLE
February 2015 meet up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#14]
**Copenhagen Elixir February 2015 meet up**

Date: February 24
Location: eTilbudavis

> Arne Jacobsens Allé 16, 3.
> DK-2300 København S
> Danmark

*If you get lost you can call Alexander Ferøy: 22133373*

Program:
  * OTP, an overview by @oscarfelipe
  * Pair programming
  * casual talk on the topic of OTP
  * show/talk about the progress of your beam project

* * *

Let's plan a meet up for February 2015.

<strike>How did you like Prototype? Should we have the meet up there again?</strike>
<strike>Should we have a set topic, or should we just have a regular conversation and see where it goes?</strike>
<strike>When would be a good date?</strike>

Also remember that there might be some Erlang related stuff at Funktionelle Københavnere meet up February 17.

**Comment by madscoaducom** [comment]
Prototype was good for the current number of attendees. Also good if we
want to actually do some work or show demos.

I think it would be good to up the game and set a topic. How about setting
topic to OTP, and the asking 2-3 people to bring a small otp-related demo ?

As for dates, I suggest Tuesday 24. or Wedensday 25.

**Comment by skovsgaard** [comment]
Prototype seems well suited for it.

I'm definitely up for setting a topic and OTP seems like a pretty good place to start.

The 24th works best for me, date wise.

**Comment by oscarfelipe** [comment]
I agree, Prototype is a cosy place to start and both dates are OK to me.
I forgot to tell you that the meetup at Prosa the 17th of February starts at 18:00, I hope to see you there!(Farimagsgade 37A). As I mentioned yesterday, funktionelle københavner is far for being an F# centric meetup, but rather a functional programming meetup. All programming languages that enforce the use of functional programming are welcome, being the most representatives at the moment: Haskell, F#, Scala, Idris and Ocaml. This is mainly because our members are experts on those languages( those who are actively participating, we are more than 200 but only 6 active members). We would love to have other topics, so If you like functional programming languages and consider yourself a polyglot programmer, come and visit us! Probably participating with an introduction to Elixir? or an Introduction to Web development with Elixir Phoenix?

Regarding the next meetup, I think is a good idea to start with a topic...and OTP is a good one (and a huge one). I offer an introduction to OTP with an overview of gen_server and application behaviours for one of the upcoming meetups.

We all have some projects we are currently working on, so probably It could be also nice if we try some hands on session where we hack on some Erlang/Elixir topic together....?

**Comment by gausby** [comment]
Ok, let's decide on February 24, and have the meet up at Prototype (unless a ton of people shows interest in the meet up). The topic will be Introduction to OTP.

@oscarfelipe it would be great with a prepared intro talk about gen_server and behaviours if you have time and feel for it

**Comment by madsflensted** [comment]
@gausby and I had a quick chat on irc, and talked about doing some pair programming exploration of OTP. So if we have a short intro by @oscarfelipe and then we could split up and do some coding.

So if anybody has ideas for something simple that could be fit for purpose?

**Comment by oscarfelipe** [comment]
Sure, I will prepare a presentation about it and then we could solve some exercises

**Comment by gausby** [comment]
@oscarfelipe nice, I'll add it to the issue/event description. :+1:

**Comment by oscarfelipe** [comment]
Hey co-beamers, as you already know, eTilbudsavis is offering a venue. I estimate that minimum 7 persons are going to attend this time, between those : Thomas, Mads, Jonas,  Joakim, Jesper, Alexander, Peter, Shandra,  and myself. I am concerned that there is no projector on prototype, neither place enough to host more than 5 people. What do you think if we meet on eTilbudavis instead?

**Comment by skovsgaard** [comment]
That sounds like a good idea, really, if we're more than double the usual headcount.

**Comment by gausby** [comment]
I am all for. I'll update the location and tweet out an announcement if it is cool with eTilbudsavis.

**Comment by oscarfelipe** [comment]
:+1:  lovely, go ahead:
 
eTilbudavis
Arne Jacobsens Allé 16, 3.
DK-2300 København S
Danmark
if you get lost you can call Alex:
Alexander Ferøy - 22133373

**Comment by gausby** [comment]
Updated location

**Comment by ahf** [comment]
Sweet! We have projector available here as well :-)

**Comment by gausby** [comment]
Cool. Anyone wanna present something I should add to the agenda?

**Comment by gausby** [comment]
I just noticed that we haven't actually set a time. I just tweeted out 19h with @[cph_ex](https://twitter.com/cph_ex), should we commit to that?

**Comment by ahf** [comment]
Works very well for us out here :-)

**Comment by skovsgaard** [comment]
I assumed from the usual and tweeted 19h as well.

**Comment by gausby** [comment]
Thanks for a great meet up. See you at the next one #15
