### ISSUE TITLE
Elixir Nerves event

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#17]
I would like to get into some hardware hacking, and Elixir has a nice project that could be helpful.
- https://github.com/fhunleth/elixir_ale

Anyone else who want to make an event where we hack on some raspberry pi's and perhaps drink a cold ale or two?

**Comment by gausby** [comment]
I've had a talk with Labitat who might be able to host the event.

Quick notes:

  * A weekend would probably be best. Besides that days except Tuesday and Thursday are good. Tuesday is open house and thursday is the day of their weekly meeting.
  * We might want to buy some Raspberry Pi's or Beaglebones in bulk, this would require some coordination.
  * We should create a wiki page on the Labitat wiki so they can help out with the practicalities (like this page: https://labitat.dk/wiki/ESP8266_networking)

**Comment by madsflensted** [comment]
Great idea

**Comment by skovsgaard** [comment]
:+1: to the weekend suggestion (or a Tuesday). Also I can bring my own Raspberry pi if need be.

**Comment by gausby** [comment]
I think it would be best with a weekend for this event. I am thinking of this as a special event.

I want to share these links as well

  * the nerves project: http://nerves-project.org
  * @fhunleth did a talk on Erlang Factory: https://www.youtube.com/watch?v=tCg1LakJF3g

**Comment by madsflensted** [comment]
And this just arrived on the scene: http://cellulose.io/getting-started/

**Comment by gausby** [comment]
Adding a link to Frank's modified SumoBot Jr. There's a shopping list as well.

  * https://github.com/fhunleth/elixirbot

Might be a project we could build on the day. Labitat might have all the tools needed. Gotta check up on that.

**Comment by fhunleth** [comment]
Just saw this - more SumoBot Jr.'s would be awesome! To my knowledge, I've uploaded everything needed to build the ElixirBot, but I never tested my instructions. I am certain that they are incomplete and could use some TLC. The parts that will probably be the trickiest are the laser cut wood pieces. I used a 45 W Full Spectrum laser to cut them. I know that an Epilog or Universal would work, but you may need to change the line colors in the drawing for it to work. The PCB can be ordered from OSH Park. Also, I found at after my presentation at EF2015 that the Raspberry Pi doesn't support I2C clock stretching. My ATtiny85 program does stretch the clock. I think that this can be fixed by optimizing the ATtiny85 code, but I didn't do it. The result is that you'll get random I2C errors. The good news is that the both bots I built worked pretty well in spite of the errors, but I find them very unnerving and sloppy. If you don't have anyone comfortable with microcontrollers around, I might suggest a simpler first project (even though that makes me sad).

Anyway, I'm thrilled that you're talking about an Elixir and hardware hacking event. I wish that I could make it!

**Comment by gausby** [comment]
@fhunleth Well. I don't have much hardware hacking experience myself; actually I guess it amounts to watching your presentation at EF. I am talking to the local hackerspace, and they definitely have the hardware hacking skills, plus they would like some software development events at their place, so it is definitely a fit—even though they think that Erlang and Elixir are some weirdo languages.

Personally I would be happy if I could just attach a motion sensor to a Raspberry PI and make it send a message to a process mailbox in Elixir. That sounds simple enough ^_^ But perhaps some of the Labitat (the hackerspace) people could look through your build and perhaps some of them know about how to optimise the ATtiny85 code.

Thanks for taking time to add to this thread :)

**Comment by fhunleth** [comment]
In that case, hooking up a PIR sensor like http://www.adafruit.com/products/189 to a GPIO should be really easy on the hardware side. The ultrasonic range finders that I know of require analog inputs so you'd need an ADC to get those to work. The Elixir ALE docs show how to use the MCP3203 ADC (although using the old binary syntax - I need to fix that). I'd go that way. You'll have a higher chance of success and prep will be easier.

**Comment by gausby** [comment]
This idea has been around for a while; I've renamed it from Ale to Nerves ^_^

I still think it would be nice to go forwards with it :)

**Comment by valberg** [comment]
Sounds like a really neat thing to play with! I'm in 👏
