### ISSUE TITLE
Elixir Meetup August '23

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#67]
# August 2023 meetup

[Sign up via Meetup!](https://www.meetup.com/copenhagen-elixir-meetup-group/events/295170307/) 

## Date and time
 17th of August - 17:30

## Topic(s)

- Ahmad Sattar: NIFs
- @erikmejerhansen: Something about `gen_statem`

## Location:
To be determined

## Agenda:

- Intro
- Talk 1: Ahmad
- Talk 2: Erik
- TBD

**Comment by killerkiara** [comment]
I will not be able to make it this month as I am leaving for holidays soon. You guys have fun and see you next month! :)

**Comment by ErikMejerHansen** [comment]
Enjoy your holiday @killerkiara ☀️

**Comment by ErikMejerHansen** [comment]
I had hoped to host the August meetup at Maersk's offices at Esplanaden, but turns out that is more complicated than expected. Anyone able to host?

**Comment by jacobat** [comment]
Karnov would like to offer hosting in our offices close to Nørreport. Message me on Slack if this sounds good.

**Comment by gausby** [comment]
I've noticed that the RSVP is closed on the Meetup dot com page—have we reached the maximum capacity for the venue? If not, I guess having the RSVP closed will discourage people from joining tomorrow.

**Comment by Straffern** [comment]
I wont be able to join anyway, I have to stay home and care for my son, because my gf is sick.

**Comment by ErikMejerHansen** [comment]
Good call @gausby. I'll change that for the next round. Don't think we'll run into capacity issues with the amount of folks we've seen the last couple of times.

**Comment by thehabbos007** [comment]
Thanks for the fun meetup! I have pushed slides/code for my presentation to https://github.com/thehabbos007/nifty if anyone is interested :)

**Comment by ErikMejerHansen** [comment]
Great talk @thehabbos007! Thanks for sharing the slides. 
I've pushed files for the `:cowboy rest handlers` talk from last month and todays presentation here: https://github.com/ErikMejerHansen/cphex_presentations

**Comment by gausby** [comment]
Thanks for organising this meetup. I am looking forward to the next one!

I posted some photos to my Mastodon. Let me know if any of you want the original files. https://mastodon.xyz/@gausby/110906687355253286

**Comment by Munksgaard** [comment]
Copying this here from the Slack for completeness:

Here's what I did to use timestamptz in my migrations and phoenix project:

 1. Configure my repo to use timestamptz for timestamps:

```elixir
# Configure the repo (in config/config.exs)
config :my_app, MyApp.Repo,
  migration_timestamps: [ type: :timestamptz ]
```

 2. Define a new schema module that overrides timestamp_opts:

```elixir
# Define a module to be used as base
#
# The purpose of this schema is to use utc_datetime for timestamps by default.
defmodule MyApp.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema

      @timestamps_opts [type: :utc_datetime]
    end
  end
end
```

 3. Use MyApp.Schema in contexts instead of Ecto.Schema, e.g:

```elixir
defmodule MyApp.User do
  use MyApp.Schema

  schema "users" do
    field :email, :text, null: false

    timestamps()
  end
end
```

As an alternative to defining a new Schema module, you can use `timestamps(type: :timestamptz)` in all your schemas. 

Following the talk we had at the meetup, I should probably change `:utc_datetime` to `:utc_datetime_usec` in `MyApp.Schema`, but that can be done without any migrations.

I'm not sure if this is the best way to handle time, but it has worked fine for me so far. I'm very open for inputs and suggestions for improvements :smile:
