### ISSUE TITLE
Elixir Meetup October '23

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#69]
# October 2023 meetup

## Date and time
19th of October 2023 - 17:30 - ~19:00

## Topic(s)
- @Munksgaard Deploying Elixir apps with Nix **or** Futlixir in-progress tool for running [Futhark](https://futhark-lang.org/) programs from Elixir
- To Be Determined: Have a idea for a topic or talk? 
## Location:
[Copenhagen FinTech Lab](https://goo.gl/maps/vXU1BDvtMthLU4Vk7)

**Comment by ErikMejerHansen** [comment]
I will have to miss this one. The kids have fall break that week. @guillego @vanjacosic

**Comment by joeljuca** [comment]
Hi,

Is this open for non-Danish participants? I don't live in Copenhagen but I would like to attend and watch.

**Comment by vanjacosic** [comment]
Enjoy the time off, Erik! 

@joeljuca Absolutely! All talks are in English and we all speak English by default, because many members are not native Danish speakers. Hope you can join us 😊

@simonelnahas You mentioned that you might be able to book the same room again, is that right? Since we don't have any other venue offers yet, it would be good to know if it is a backup option for this month - it's a great space

Does anyone else have something they'd like to share? Doesn't have to be a "full talk", could be a demo or show and tell

**Comment by ErikMejerHansen** [comment]
@vanjacosic We found a location, @Munksgaard has booked the lounge at [Copenhagen FinTech Lab](https://goo.gl/maps/vXU1BDvtMthLU4Vk7)

**Comment by joeljuca** [comment]
@vanjacosic is this meetup IRL, virtual, or hybrid? :)

**Comment by ErikMejerHansen** [comment]
> @vanjacosic is this meetup IRL, virtual, or hybrid? :)

In real life

**Comment by grych** [comment]
Hey guys, 
I was the first time for it, and I will be the next time :)

**Comment by Munksgaard** [comment]
Thanks for coming, everyone! I forgot to put include a link to futlixir, so [here you are](https://github.com/Munksgaard/futlixir). Although, I should probably rename it to futler now. Also, here's the link to [Futhark](https://futhark-lang.org/).

Edit: And here is the "presentation" I used: https://gist.github.com/Munksgaard/cf4978cacd293cd55b29113facf33453
